## Exercício 16 – Menu de opções

Peça ao usuário para digitar uma opção:

1 – Olá
2 – Bem-vindo
3 – Python

Mostre a mensagem correspondente à opção escolhida.

Caso a opção não exista, mostre **"Opção inválida"**.

---

## Exercício 17 – Calculadora simples

Peça ao usuário:

* primeiro número
* segundo número
* operação (`+`, `-`, `*`, `/`)

Use `match-case` para executar a operação escolhida.

---

## Exercício 18 – Dia da semana

Peça ao usuário um número de **1 a 7**.

Mostre o dia correspondente:

1 – Domingo
2 – Segunda
3 – Terça
4 – Quarta
5 – Quinta
6 – Sexta
7 – Sábado

---

## Exercício 19 – Menu de bebidas

Peça ao usuário para escolher:

1 – Água
2 – Refrigerante
3 – Suco
4 – Café

Mostre a bebida selecionada e o preço de cada uma de acordo com a tabela abaixo:

Água = R$ 4,00
Refrigerante = R$ 8,00
Suco = R$ 10,00
Café = R$ 5,00

---

## Exercício 20 – Classificação de letra

Peça ao usuário uma letra.

Use `match-case` para verificar:

* `a`, `e`, `i`, `o`, `u` → **Vogal**
* qualquer outra letra → **Consoante**

---

## Exercício 21 – Menu de cores

Peça ao usuário um número:

1 – Vermelho
2 – Azul
3 – Verde
4 – Amarelo

Mostre o nome da cor correspondent e se é uma cor quente ou fria

---

## Exercício 22 – Conversão de temperatura

Peça ao usuário:

* valor da temperatura
* tipo de conversão (`C`, `F`, `K`)

Use `match-case` para escolher a conversão.

Exemplo:

* C → Celsius para Fahrenheit
* F → Fahrenheit para Celsius
* K → Kelvin para Celsius

---

## Exercício 23 – Classificação de notas

Peça ao usuário para digitar uma **letra de conceito**:

A
B
C
D
F

Mostre a classificação correspondente:

* A → Excelente
* B → Bom
* C → Regular
* D → Ruim
* F → Reprovado

---